image: node:alpine
pipelines:
  branches:
    master:
      - step:
          name: Syntax checking (eslint)
          script:
            - yarn
            - yarn lint
      - step:
          name: Unit Testing (jest)
          script:
            - yarn
            - yarn test
